package Reports;
// Importing necessary classes for generating Cucumber reports
import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

// This class is responsible for generating advanced Cucumber reports
public class GenerateReport {

    public static void main(String[] args) {
        // Define the output directory for the report
        File reportOutputDirectory = new File("target/advanced-cucumber-reports");

        // List to store the paths of JSON files generated by the Cucumber test execution
        List<String> jsonFiles = new ArrayList<>();
        jsonFiles.add("target/cucumber.json");// Add the JSON report generated by Cucumber tests

        String buildNumber = "1";
        String projectName = "VF_CZ_TASK";

        Configuration configuration = new Configuration(reportOutputDirectory, projectName);
        configuration.setBuildNumber(buildNumber);
        configuration.addClassifications("Browser", "Chrome");
        configuration.addClassifications("Platform", "Windows 11");
        configuration.addClassifications("Java Version", "22.0.1");

        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();
    }
}
